### ISSUE TITLE
OneNodeReducedCapacity with terraform and vsphere automation. 

### ISSUE THREAD

**Issue by rshade** [vmware/vsphere-automation-sdk-go#1]
I am having a problem with OneNodeReducedCapacity, if I set it to `true` I get a `com.vmware.vapi.std.errors.unauthorized`. This is probably a user error, however I am not sure where. If I look at https://vmware.github.io/vsphere-automation-sdk-rest/vmc/operations/com/vmware/vmc/orgs/sddcs.create-operation.html it suggests for post it should work. https://github.com/vmware/vsphere-automation-sdk-go/blob/master/services/vmc/model/ModelPackageTypes.go#L349 shows it to be part of the struct. My struct looks like: 
`model.AwsSddcConfig{
  Region:"US_WEST_2", 
  OneNodeReducedCapacity:(*bool)(0xc000147478), 
  VpcCidr:(*string)(0xc000278820), 
  HostInstanceType:(*model.HostInstanceTypes)(0xc000278b60), 
  SkipCreatingVxlan:(*bool)(0xc00014747a), 
  VxlanSubnet:(*string)(0xc0002788e0), 
  Size:(*string)(nil), 
  StorageCapacity:(*int64)(0xc000147468), 
  Name:"rstest", 
  AccountLinkSddcConfig:[]
    model.AccountLinkSddcConfig{
      model.AccountLinkSddcConfig{
        CustomerSubnetIds:[]string{"subnet-04f1bf4ea3201bce1"}, 
        ConnectedAccountId:(*string)(0xc000278b50)
        }
      }, 
  NumHosts:1, 
  SddcType:(*string)(0xc000278880), 
  AccountLinkConfig:(*model.AccountLinkConfig)(0xc000007040), 
  Provider:"AWS", 
  SsoDomain:(*string)(0xc000278990), 
  SddcTemplateId:(*string)(0xc0002789d0), 
  DeploymentType:(*string)(0xc0002789f0)
  } `

I was trying to add it to the terraform provider: https://github.com/rshade/terraform-provider-vmc/blob/add-single-node-support/vmc/resource_vmc_sddc.go#L223, any information you have would be super helpful.

**Comment by vmehtavmware** [comment]
Sorry for the delayed response, looking into it.

**Comment by vmehtavmware** [comment]
Please make sure that when NumHosts is set 1, SddcType should be set to "1NODE".
If you have set it as "1NODE" and still showing this error, I will need exact values for the struct you are using to debug it further.

**Comment by rshade** [comment]
@vmehtavmware thank you. This was my main.tf: https://github.com/rs-services/terraform-rs-vmc/blob/master/main.tf#L28, and my tf branch I was hacking against: https://github.com/vmware/terraform-provider-vmc/compare/master...rshade:add-single-node-support?expand=1, I removed the OneNodeReducedCapacity and it would provision it, add it back and fail.

**Comment by rshade** [comment]
any idea how I can get the exact values, I already tried adding spew, and that's as close as I could get.

**Comment by vmehtavmware** [comment]
> any idea how I can get the exact values, I already tried adding spew, and that's as close as I could get.

main.tf is enough to debug.

**Comment by shylasrinivas** [comment]
@rshade I tried create SDDC API call via postman with one node reduced capacity set to true and it failed with "Bad request" error. I was able to make a successful call when it is set to false. So, it looks like we are either missing some params in the request or there is an API limitation. I am following up with the VMC API team for details. Will circle back with you when we know more. Thanks for your patience.

**Comment by rshade** [comment]
@shylasrinivas thank you so much, it's good to know at least that it was reproduce-able.

**Comment by shylasrinivas** [comment]
@rshade I heard back from the API developers. One node reduced capacity feature is not released to production yet. Which environment are you trying it on?

**Comment by rshade** [comment]
@shylasrinivas definitely production. Do you think we can get them to add a comment to the api doc?

**Comment by rshade** [comment]
Also the unauthorized error might need to say `bad request`

**Comment by shylasrinivas** [comment]
@rshade thank you for the feedback
1. I have passed this on to the API team and they will file a ticket to update the swagger/openAPI spec
2. Yes, the error message is not helpful and we will look into it.

**Comment by rshade** [comment]
@shylasrinivas Thank you so much. I am going to tweak my code and remove the feature, thank you for the help.
