### ISSUE TITLE
Missing backup API

### ISSUE THREAD

**Issue by ericsoler1** [vmware/vsphere-automation-sdk-go#2]
Hi, is this the correct library for http://vmware.github.io/vsphere-automation-sdk-rest/6.5/structures/com/vmware/appliance/recovery/backup/svc.backup_request-structure.html I can't seem to find the backup api anywhere.

Thanks

**Comment by vmehtavmware** [comment]
Hi,
vSphere APIs are not yet supported. We will be adding the support for vSphere APIs soon.
Regards,
Vandit Mehta.
